# Generated by Django 2.1.5 on 2019-01-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='origin',
            field=models.CharField(default='Methodical', max_length=100),
        ),
    ]
